version: 2

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "08:00"
    timezone: Asia/Jakarta
  open-pull-requests-limit: 100
  reviewers:
  - berviantoleo
  assignees:
  - berviantoleo
  groups:
    dev:
      dependency-type: development

- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: "weekly"
    time: "08:00"
    day: "saturday"
    timezone: Asia/Jakarta
  open-pull-requests-limit: 100
