version: 2
registries:
  npm-registry-npm-pkg-github-com:
    type: npm-registry
    url: https://npm.pkg.github.com
    username: "${{secrets.NPM_REGISTRY_NPM_PKG_GITHUB_COM_USERNAME}}"
    password: "${{secrets.NPM_REGISTRY_NPM_PKG_GITHUB_COM_PASSWORD}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "08:00"
    timezone: Asia/Jakarta
  open-pull-requests-limit: 100
  reviewers:
  - berviantoleo
  assignees:
  - berviantoleo
  ignore:
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.13.8
  - dependency-name: eslint-config-prettier
    versions:
    - 8.1.0
  - dependency-name: eslint
    versions:
    - 7.21.0
  - dependency-name: rollup-plugin-typescript2
    versions:
    - 0.30.0
  registries:
  - npm-registry-npm-pkg-github-com
