version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  build:
    docker: # run the steps with Docker
      - image: cimg/node:lts # ...with this image as the primary container; this is where all `steps` will run
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '18.12'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-dependencies-run
          command: yarn --frozen-lockfile
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: # run coverage report
          name: code-coverage
          command: yarn lint
      - run: # run compiler
          name: compile
          command: yarn build
      - run: # run test
          name: test
          command: yarn test
