name: Node CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [12.x, 14.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install, test, build
      run: |
        yarn
        yarn test
        yarn build
      env:
        CI: true
    - uses: codecov/codecov-action@v1
      if: ${{ matrix.node-version == '14.x'}}
    - name: Release
      if: ${{ github.event_name == 'push' && matrix.node-version == '14.x' }}
      run: npx semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
