name: Node CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [14.x, 16.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://npm.pkg.github.com'
        scope: '@bervproject'
        always-auth: true
    - name: Build, Test and Generate Docs
      run: |
        yarn --frozen-lockfile
        yarn lint
        yarn test
        yarn build
        yarn docs
      env:
        CI: true
    - uses: codecov/codecov-action@v1
      if: ${{ matrix.node-version == '14.x'}}
    - name: Release
      if: ${{ github.event_name == 'push' && matrix.node-version == '14.x' }}
      run: npx semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Docs Deploy
      if: ${{ github.event_name == 'push' && matrix.node-version == '14.x' }}
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
    - name: Use Node.js ${{ matrix.node-version }}
      if: ${{ github.event_name == 'push' && matrix.node-version == '14.x' }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://registry.npmjs.org'
        scope: '@bervproject'
        always-auth: true
    - name: Publish to NPM
      if: ${{ github.event_name == 'push' && matrix.node-version == '14.x' }}
      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
